bedrock.agent.id=${BEDROCK_AGENT_ID:AAQOIDRFC4}
bedrock.agent.alias-id=${BEDROCK_AGENT_ALIAS_ID:DQGIMY5XSE}
logging.level.dev.coderats.backend.service.GitHubCommitService=DEBUG
logging.level.dev.coderats.backend.service.CommitEvaluationService=DEBUG
