spring.profiles.active=${SPRING_PROFILES_ACTIVE}

# --- DATASOURCE ---
spring.datasource.url=${DB_URL:jdbc:postgresql://3.128.30.149:5432/coderats_db}
spring.datasource.username=${DB_USER:coderats_user}
spring.datasource.password=${DB_PASS:coderats_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hikari (opcional, mas ajuda em dev)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

# --- FLYWAY ---
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.clean-disabled=true

# --- GitHub OAuth --- 
github.oauth.client-id=${GITHUB_OAUTH_CLIENT_ID_DEV}
github.oauth.client-secret=${GITHUB_OAUTH_CLIENT_SECRET_DEV}
github.oauth.redirect-uri=${GITHUB_OAUTH_REDIRECT_URI_DEV}

# application.properties
spring.config.import=optional:file:.env[.properties]
logging.level.org.springframework.boot.context.config=DEBUG

aws.region=${AWS_REGION:us-east-2}
bedrock.agent.id=${BEDROCK_AGENT_ID:AAQOIDRFC4}
bedrock.agent.alias-id=${BEDROCK_AGENT_ALIAS_ID:DQGIMY5XSE}

logging.level.dev.coderats.backend.service.GitHubCommitService=DEBUG
