-- MySQL Script generated by MySQL Workbench
-- Sun Sep 28 17:18:42 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario` ;

CREATE TABLE IF NOT EXISTS `Usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(120) NOT NULL,
  `senha` VARCHAR(120) NOT NULL,
  `nome` VARCHAR(120) NOT NULL,
  `imagem` VARCHAR(255) NULL,
  `usuario_github` VARCHAR(120) NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `usuario_github_UNIQUE` (`usuario_github` ASC) VISIBLE,
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Grupo` ;

CREATE TABLE IF NOT EXISTS `Grupo` (
  `id_grupo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `codigo` CHAR(10) NOT NULL,
  `imagem` VARCHAR(255) NULL,
  `metodo` VARCHAR(255) NOT NULL,
  `repositorio` VARCHAR(255) NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id_grupo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) VISIBLE,
  UNIQUE INDEX `id_grupo_UNIQUE` (`id_grupo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Check_in`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Check_in` ;

CREATE TABLE IF NOT EXISTS `Check_in` (
  `id_checkin` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(120) NOT NULL,
  `data` DATETIME NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `foto` VARCHAR(255) NULL,
  `pontos` INT NOT NULL DEFAULT 0,
  ` resumo_ia` VARCHAR(255) NULL,
  `fk_id_usuario` INT NOT NULL,
  `fk_id_grupo` INT NOT NULL,
  PRIMARY KEY (`id_checkin`, `fk_id_usuario`, `fk_id_grupo`),
  UNIQUE INDEX `id_checkin_UNIQUE` (`id_checkin` ASC) VISIBLE,
  INDEX `fk_Check_in_Usuario1_idx` (`fk_id_usuario` ASC) VISIBLE,
  INDEX `fk_Check_in_Grupo1_idx` (`fk_id_grupo` ASC) VISIBLE,
  CONSTRAINT `fk_Check_in_Usuario1`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Check_in_Grupo1`
    FOREIGN KEY (`fk_id_grupo`)
    REFERENCES `Grupo` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Commits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Commits` ;

CREATE TABLE IF NOT EXISTS `Commits` (
  `id_commit` INT NOT NULL AUTO_INCREMENT,
  `link` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_commit`),
  UNIQUE INDEX `id_commit_UNIQUE` (`id_commit` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Comentario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Comentario` ;

CREATE TABLE IF NOT EXISTS `Comentario` (
  `id_comentario` INT NOT NULL AUTO_INCREMENT,
  `conteudo` VARCHAR(255) NOT NULL,
  `data_criacao` DATETIME NOT NULL,
  `fk_id_usuario` INT NOT NULL,
  `fk_id_checkin` INT NOT NULL,
  PRIMARY KEY (`id_comentario`, `fk_id_usuario`, `fk_id_checkin`),
  UNIQUE INDEX `id_comentario_UNIQUE` (`id_comentario` ASC) VISIBLE,
  INDEX `fk_Comentario_Usuario1_idx` (`fk_id_usuario` ASC) VISIBLE,
  INDEX `fk_Comentario_Check_in1_idx` (`fk_id_checkin` ASC) VISIBLE,
  CONSTRAINT `fk_Comentario_Usuario1`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentario_Check_in1`
    FOREIGN KEY (`fk_id_checkin`)
    REFERENCES `Check_in` (`id_checkin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Curtida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Curtida` ;

CREATE TABLE IF NOT EXISTS `Curtida` (
  `id_curtida` INT NOT NULL AUTO_INCREMENT,
  `status` TINYINT NOT NULL DEFAULT 0,
  `fk_id_usuario` INT NOT NULL,
  `fk_id_checkin` INT NOT NULL,
  PRIMARY KEY (`id_curtida`, `fk_id_usuario`, `fk_id_checkin`),
  UNIQUE INDEX `id_curtida_UNIQUE` (`id_curtida` ASC) VISIBLE,
  INDEX `fk_Curtida_Usuario1_idx` (`fk_id_usuario` ASC) VISIBLE,
  INDEX `fk_Curtida_Check_in1_idx` (`fk_id_checkin` ASC) VISIBLE,
  CONSTRAINT `fk_Curtida_Usuario1`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curtida_Check_in1`
    FOREIGN KEY (`fk_id_checkin`)
    REFERENCES `Check_in` (`id_checkin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Badge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Badge` ;

CREATE TABLE IF NOT EXISTS `Badge` (
  `id_badge` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `imagem` VARCHAR(255) NULL,
  `pontos` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_badge`),
  UNIQUE INDEX `id_badge_UNIQUE` (`id_badge` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Usuario_Pertence_Grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario_Pertence_Grupo` ;

CREATE TABLE IF NOT EXISTS `Usuario_Pertence_Grupo` (
  `fk_id_usuario` INT NOT NULL,
  `fk_id_grupo` INT NOT NULL,
  `pontos` INT NOT NULL DEFAULT 0,
  `admin` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`fk_id_usuario`, `fk_id_grupo`),
  INDEX `fk_Usuario_has_Grupo_Grupo1_idx` (`fk_id_grupo` ASC) VISIBLE,
  INDEX `fk_Usuario_has_Grupo_Usuario_idx` (`fk_id_usuario` ASC) VISIBLE,
  UNIQUE INDEX `admin_UNIQUE` (`admin` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_Grupo_Usuario`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Grupo_Grupo1`
    FOREIGN KEY (`fk_id_grupo`)
    REFERENCES `Grupo` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Check_in_possui_Commits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Check_in_possui_Commits` ;

CREATE TABLE IF NOT EXISTS `Check_in_possui_Commits` (
  `fk_id_checkin` INT NOT NULL,
  `Check_in_fk_id_usuario` INT NOT NULL,
  `Check_in_fk_id_grupo` INT NOT NULL,
  `fk_id_commit` INT NOT NULL,
  PRIMARY KEY (`fk_id_checkin`, `Check_in_fk_id_usuario`, `Check_in_fk_id_grupo`, `fk_id_commit`),
  INDEX `fk_Check_in_has_Commits_Commits1_idx` (`fk_id_commit` ASC) VISIBLE,
  INDEX `fk_Check_in_has_Commits_Check_in1_idx` (`fk_id_checkin` ASC, `Check_in_fk_id_usuario` ASC, `Check_in_fk_id_grupo` ASC) VISIBLE,
  CONSTRAINT `fk_Check_in_has_Commits_Check_in1`
    FOREIGN KEY (`fk_id_checkin` , `Check_in_fk_id_usuario` , `Check_in_fk_id_grupo`)
    REFERENCES `Check_in` (`id_checkin` , `fk_id_usuario` , `fk_id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Check_in_has_Commits_Commits1`
    FOREIGN KEY (`fk_id_commit`)
    REFERENCES `Commits` (`id_commit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Usuario_possui_Badge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario_possui_Badge` ;

CREATE TABLE IF NOT EXISTS `Usuario_possui_Badge` (
  `fk_id_badge` INT NOT NULL,
  `fk_id_usuario` INT NOT NULL,
  PRIMARY KEY (`fk_id_badge`, `fk_id_usuario`),
  INDEX `fk_Badge_has_Usuario_Usuario1_idx` (`fk_id_usuario` ASC) VISIBLE,
  INDEX `fk_Badge_has_Usuario_Badge1_idx` (`fk_id_badge` ASC) VISIBLE,
  CONSTRAINT `fk_Badge_has_Usuario_Badge1`
    FOREIGN KEY (`fk_id_badge`)
    REFERENCES `Badge` (`id_badge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Badge_has_Usuario_Usuario1`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
