

services:
  db:
    image: postgres:16
    container_name: coderats_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 15

  pgadmin:
    image: dpage/pgadmin4
    container_name: coderats_pgadmin
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin:/var/lib/pgadmin

  backend:
    build: ./apps/backend
    container_name: coderats_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "${APP_PORT}:8080"

  mobile:
    build: ./apps/mobile
    container_name: coderats-mobile
    # network_mode: "host"
    user: flutteruser
    ports:
      - "8081:8080"  
    volumes:
      - ./apps/mobile:/home/flutteruser/app
    tty: true
    dns:
      - 8.8.8.8
      - 8.8.4.4
    stdin_open: true
    command: sh

volumes:
  pgdata:
  pgadmin:
